"use client";
//Generated by GeneratePageFile
import React, { useState } from "react";
import { useDarkModeStore } from "../../stores/dark-mode";

const DarkLightToggle: React.FC = () => {
  const { darkMode, toggleDarkMode } = useDarkModeStore();
  return (
    <div
      className="border-[2.5px] border-green-900 rounded-[30px] flex justify-between items-center p-1 relative gap-2 cursor-pointer text-sm select-none"
      onClick={toggleDarkMode}
    >
      <div>☀️</div>
      <div>🌙</div>
      <div
        className={`absolute h-[22px] w-[22px] bg-green-700 rounded-full transition-all ease-in-out duration-150 ${
          darkMode ? "left-1" : "left-7"
        }`}
      ></div>
    </div>
  );
};

export default DarkLightToggle;
