//Generated by GeneratePageFile
import Image from "next/image";
import React from "react";
import Illustrations from "public/illustration.png";
import Websites from "public/websites.jpg";
import Apps from "public/apps.jpg";
import Link from "next/link";

const Portfolio: React.FC = () => {
  const portfolios = [
    {
      id: 1,
      src: Illustrations,
      alt: "Illustrations",
      href: "illustrations",
    },
    {
      id: 2,
      src: Websites,
      alt: "Websites",
      href: "websites",
    },
    {
      id: 3,
      src: Apps,
      href: "applications",
      alt: "Applications",
    },
  ];

  return (
    <div className="flex flex-col gap-10">
      <h1 className="text-4xl font-extrabold">Our Works</h1>
      <h2 className="text-lg font-bold">Choose a gallery</h2>
      <div className="flex gap-10 h-[500px] [&>*]:w-[300px] [&>*]:border-2 [&>*]:border-white">
        {portfolios.map((item) => (
          <Link
            href={`/portfolio/${item.href}`}
            key={item.id}
            className="relative group"
          >
            <Image
              src={item.src}
              alt={item.alt}
              fill={true}
              className="object-cover brightness-50 group-hover:brightness-90"
            />
            <h2 className="absolute right-5 bottom-5 font-extrabold text-slate-50 text-2xl">
              {item.alt}
            </h2>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Portfolio;
