import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";
import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import Theme from "../components/theme/Theme";

const roboto = Roboto_Flex({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Theme>
          <Header />
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
