"use client";
import { Button } from "@/components/ui/Button";
import { signOut, useSession } from "next-auth/react";
import Link from "next/link";

//Generated by GeneratePageFile
import React from "react";

const Logout: React.FC = () => {
  const { status } = useSession();

  if (status === "loading") {
    return null;
  }

  if (status === "unauthenticated") {
    return <Link href="/dashboard/login">Login</Link>;
  }

  return (
    <Button
      variant="outline"
      onClick={() => {
        signOut({
          callbackUrl: `${window.location.origin}/dashboard/login`,
        });
      }}
    >
      Logout
    </Button>
  );
};

export default Logout;
