//Generated by GeneratePageFile
import Link from "next/link";
import React from "react";
import DarkLightToggle from "../dark-light-toggle/DarkLightToggle";

const links = [
  { id: 1, name: "Home", href: "/" },
  { id: 2, name: "Portfolio", href: "/portfolio" },
  { id: 3, name: "Blog", href: "/blog" },
  { id: 4, name: "About", href: "/about" },
  { id: 5, name: "Contact", href: "/contact" },
  { id: 6, name: "Dashboard", href: "/dashboard" },
];
const Header: React.FC = () => {
  return (
    <div className="h-[100px] flex justify-between items-center">
      <Link className="text-lg font-bold" href="/">
        Pradascus
      </Link>
      <div className="flex items-center gap-10">
        <DarkLightToggle />
        {links.map((link) => (
          <Link key={link.id} href={link.href}>
            {link.name}
          </Link>
        ))}
        <button className="px-4 py-1 text-white bg-green-600 rounded sm">
          Logout
        </button>
      </div>
    </div>
  );
};

export default Header;
