"use client";
import { Button } from "@/components/ui/Button";
import { signOut, useSession } from "next-auth/react";
import Link from "next/link";

//Generated by GeneratePageFile
import React from "react";

const SessionButton: React.FC = () => {
  const { status, data } = useSession();

  if (status === "unauthenticated" || status === "loading") {
    return (
      <Button
        variant="outline"
        asChild
        className="rounded-full dbg-secondary dark:hover:bg-slate-950"
        disabled={status === "loading"}
      >
        <Link href="/dashboard/login">Login</Link>
      </Button>
    );
  }

  return (
    <Button
      variant="outline"
      onClick={() => {
        signOut({
          callbackUrl: `${window.location.origin}/dashboard/login`,
        });
      }}
      className="rounded-full bg-secondary hover:bg-slate-950"
    >
      Logout
    </Button>
  );
};

export default SessionButton;
