"use client";
//Generated by GeneratePageFile
import React from "react";
import { useDarkModeStore } from "../../stores/dark-mode";

interface ThemeProps {
  children: React.ReactNode;
}

const Theme: React.FC<ThemeProps> = ({ children }) => {
  const { darkMode } = useDarkModeStore();
  return (
    <div className={`${darkMode ? "dark" : ""}`}>
      <div className="transition-all duration-200 ease-in-out bg-slate-50 dark:bg-slate-950 text-slate-950 dark:text-slate-100">
        <div className="min-h-screen max-w-screen-xl mx-auto flex flex-col [&>*]:px-7 [&>*:nth-child(2)]:flex-1">
          {children}
        </div>
      </div>
    </div>
  );
};

export default Theme;
