//Generated by GeneratePageFile
import React from "react";
import LinkButton from "../../../components/LinkButton";
import Image from "next/image";

interface CategoryProps {
  params: {
    category: string;
  };
}

const work = {
  title: "Creative Portfolio",
  description: `A creative portfolio is a curated collection of an individual's or a group's creative works, showcasing their skills, talents, and accomplishments in various artistic disciplines. It serves as a visual and tangible representation of their creative journey and serves as a powerful tool for self-expression and professional development. A creative portfolio often includes a diverse range of mediums such as graphic design, illustration, photography, painting, sculpture, writing, and more. It captures the essence of an artist's unique style, their ability to think outside the box, and their capacity to bring imagination to life. A well-crafted creative portfolio not only displays the technical proficiency of an artist but also demonstrates their ability to communicate ideas, evoke emotions, and engage with their audience on a deeper level.
    
    A creative portfolio is not merely a compilation of artworks but a narrative that tells the story of an artist's growth, inspirations, and creative process. It is a visual and conceptual journey that allows viewers to delve into the artist's world, gain insights into their artistic vision, and experience their unique perspective. Each piece in the portfolio reflects the artist's distinct artistic voice and their willingness to experiment, innovate, and push boundaries. A successful creative portfolio not only captivates its audience but also leaves a lasting impression, showcasing the artist's dedication, versatility, and passion for their craft. It serves as a testament to their creative potential and acts as a powerful tool for establishing connections, securing opportunities, and carving out a niche in the competitive creative industry.`,
  src: "artwork.jpg",
};
const emptyArr = ["", "", ""];

const Category: React.FC<CategoryProps> = ({ params }) => {
  return (
    <div className="flex flex-col justify-center flex-1 w-full max-w-screen-lg gap-5 px-4 mx-auto">
      <h1 className="font-extrabold text-7xl">Our Works</h1>
      <h3 className="text-3xl font-bold uppercase">{params.category}</h3>
      {emptyArr.map((item, i) => {
        const flexClass = i % 2 === 0 ? "flex" : "flex flex-row-reverse";
        return (
          <div className={flexClass + " gap-5 pb-20"} key={i}>
            <div className="flex flex-col self-center flex-1 gap-5">
              <h2 className="text-2xl font-bold">{work.title}</h2>
              <p>{work.description}</p>
              <LinkButton href="/" text="See more" />
            </div>
            <div className="relative flex-1">
              <Image
                src={`/${work.src}`}
                alt={work.src}
                fill={true}
                className="object-contain"
              />
            </div>
          </div>
        );
      })}
    </div>
  );
};

export default Category;
