"use client";
//Generated by GeneratePageFile
import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from "@tanstack/react-query";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import axiosClient from "../../utils/api";
import axios from "axios";
import { cn } from "@/lib/utils";

export interface TPost {
  userId: number;
  id: number;
  title: string;
  body: string;
}

// Create a client
const queryClient = new QueryClient();

//prettier-ignore
const BlogPage: React.FC = () => {
  
  return (
    <QueryClientProvider client={queryClient}>
      <Blogs />
    </QueryClientProvider>
    
  );
};

const containerClasses = cn(
  "flex flex-col flex-1 w-full max-w-screen-lg gap-20 px-4 mx-auto"
);

const Blogs: React.FC = () => {
  const { data, isLoading, isError, error, isFetching } = useQuery({
    queryKey: ["posts"],
    queryFn: async () => {
      const { data } = await axiosClient.get("/posts");
      return data;
    },
    retry: 1,
  });

  if (isError) {
    return <div className={containerClasses}>Error bitch!</div>;
  }

  if (isLoading) {
    return <div className={containerClasses}>I'm loading</div>;
  }

  const blogs = data as unknown as {
    status: "string";
    data: { rows: TPost[] };
  };

  return (
    <div className={containerClasses}>
      {blogs.data.rows.map((blog) => (
        <div className="flex gap-5" key={blog.id}>
          <div className="relative">
            <Image
              src={`/blog-${blog.id}.jpg`}
              alt={`blog-${blog.id}`}
              width={400}
              height={250}
              className="object-cover"
            />
          </div>
          <div className="flex flex-col flex-1 gap-5">
            <Link href={"/blog/" + blog.id} className="text-3xl font-extrabold">
              {blog.title}
            </Link>
            <p className="text-lg">{blog.body}</p>
          </div>
        </div>
      ))}
    </div>
  );
};

export default BlogPage;
