//Generated by GeneratePageFile
import Image from "next/image";
import Link from "next/link";
import React from "react";

export interface TBlog {
  userId: number;
  id: number;
  title: string;
  body: string;
}

async function getData() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts", {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

//prettier-ignore
//@ts-expect-error Async Server Component
const Blog: React.FC = async () => {
  const blogs = (await getData()) as unknown as TBlog[];

  return (
    <div className="flex flex-col gap-20">
      {blogs.map((blog) => (
        <div className="flex gap-5" key={blog.id}>
          <div className="relative">
            <Image
              src={`/blog-${blog.id}.jpg`}
              alt={`blog-${blog.id}`}
              width={400}
              height={250}
              className="object-cover"
            />
          </div>
          <div className="flex flex-col flex-1 gap-5">
            <Link href={"/blog/" + blog.id} className="text-3xl font-extrabold">
              {blog.title}
            </Link>
            <p className="text-lg">{blog.body}</p>
          </div>
        </div>
      ))}
    </div>
  );
};

export default Blog;
