"use client";
//Generated by GeneratePageFile
import { signIn } from "next-auth/react";
import React from "react";
import loginSchema from "@/schema/login";
import {
  QueryClient,
  QueryClientProvider,
  useMutation,
} from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { ErrorMessage, Field, Form, Formik, FormikHelpers } from "formik";
import Link from "next/link";
import { Icons } from "@/components/Icons";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";

interface FormValues {
  emailOrUsername: string;
  password: string;
}

// Create a QueryClient instance
const queryClient = new QueryClient();

const Login: React.FC = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <LoginForm />
    </QueryClientProvider>
  );
};

const LoginForm: React.FC = () => {
  const router = useRouter();

  const initialValues: FormValues = {
    emailOrUsername: "jet_pradas",
    password: "Jetpogi_21",
  };

  const login = async (values: FormValues) => {
    const result = await signIn("credentials", {
      ...values,
      callbackUrl: "/dashboard",
    });
  };

  const { mutate, isLoading } = useMutation(login, {
    onSuccess: (data) => {
      //router.push("/dashboard");
    },
    onError: (error) => {
      console.log({ error });
    },
  });

  const handleSubmit = async (
    values: FormValues,
    { setSubmitting }: FormikHelpers<FormValues>
  ) => {
    // Use useMutation here from react-query
    mutate(values);
    setSubmitting(false);
  };

  return (
    <div className="flex flex-col items-center flex-1 text-sm w-full max-w-[500px] mx-auto">
      <h1 className="my-5 text-5xl">Login</h1>
      <Formik
        initialValues={initialValues}
        validationSchema={loginSchema}
        onSubmit={handleSubmit}
        validateOnChange={false}
      >
        {({ isSubmitting, submitForm }) => (
          <form
            className="flex flex-col gap-4 w-full px-4 md:w-[400px]"
            onSubmit={(e) => {
              e.preventDefault();
              submitForm();
            }}
          >
            <Field
              type="text"
              name="emailOrUsername"
              placeholder="Email or Username"
              as={Input}
              required
            />
            <ErrorMessage
              name="emailOrUsername"
              component="div"
              className="text-sm text-red-500"
            />

            <Field
              type="password"
              name="password"
              placeholder="Password"
              as={Input}
              required
            />
            <ErrorMessage
              name="password"
              component="div"
              className="text-sm text-red-500"
            />
            <span className="text-right">Forgot password?</span>
            <Button
              type="submit"
              variant="secondary"
              disabled={isSubmitting || isLoading}
              className="rounded-full"
            >
              Login
            </Button>
            <span className="py-2 font-bold text-center">Or</span>
            <Button
              variant={"secondary"}
              onClick={(e) => {
                e.preventDefault();
                signIn("google", {
                  callbackUrl: `${window.location.origin}/dashboard`,
                });
              }}
              disabled={isSubmitting || isLoading}
              className="relative font-bold tracking-wider rounded-full"
            >
              <Icons.google className="absolute w-5 h-5 left-4" /> Continue with
              Google
            </Button>
            <Link
              href="/dashboard/register"
              className="text-center text-primary"
            >
              Register for an account
            </Link>
          </form>
        )}
      </Formik>
    </div>
  );
};

export default Login;
