"use client";

//Generated by GeneratePageFile
import { signIn } from "next-auth/react";
import React from "react";
import loginSchema from "@/schema/login";
import {
  QueryClient,
  QueryClientProvider,
  useMutation,
} from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { ErrorMessage, Field, Form, Formik, FormikHelpers } from "formik";
import Link from "next/link";
import TWInput from "@/components/ui/input/TWInput";
import TWButton from "@/components/ui/input/TWButton";

interface FormValues {
  emailOrUsername: string;
  password: string;
}

// Create a QueryClient instance
const queryClient = new QueryClient();

const Login: React.FC = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <LoginForm />
    </QueryClientProvider>
  );
};

const LoginForm: React.FC = () => {
  const router = useRouter();

  const initialValues: FormValues = {
    emailOrUsername: "jet_pradas",
    password: "Jetpogi_21",
  };

  const login = async (values: FormValues) => {
    const result = await signIn("credentials", {
      ...values,
      callbackUrl: "/dashboard",
    });
  };

  const { mutate, isLoading } = useMutation(login, {
    onSuccess: (data) => {
      //router.push("/dashboard");
    },
    onError: (error) => {
      console.log({ error });
    },
  });

  const handleSubmit = async (
    values: FormValues,
    { setSubmitting }: FormikHelpers<FormValues>
  ) => {
    console.log("🚀 ~ file: page.tsx:61 ~ values:", values);
    // Use useMutation here from react-query
    mutate(values);
    setSubmitting(false);
  };

  return (
    <div className="flex items-center justify-center">
      <Formik
        initialValues={initialValues}
        validationSchema={loginSchema}
        onSubmit={handleSubmit}
        validateOnChange={false}
      >
        {({ isSubmitting, submitForm }) => (
          <form
            className="flex flex-col gap-4 w-[500px]"
            onSubmit={(e) => {
              e.preventDefault();
              console.log("submitted");
              submitForm();
            }}
          >
            <Field
              type="text"
              name="emailOrUsername"
              placeholder="Email or Username"
              as={TWInput}
              required
            />
            <ErrorMessage
              name="emailOrUsername"
              component="div"
              className="text-sm text-red-500"
            />

            <Field
              type="password"
              name="password"
              placeholder="Password"
              as={TWInput}
              required
            />
            <ErrorMessage
              name="password"
              component="div"
              className="text-sm text-red-500"
            />

            <TWButton
              type="submit"
              variant="contained"
              disabled={isSubmitting || isLoading}
            >
              Login
            </TWButton>
            <TWButton
              variant="contained"
              onClick={(e) => {
                e.preventDefault();
                signIn("google", {
                  callbackUrl: `${window.location.origin}/dashboard`,
                });
              }}
              disabled={isSubmitting || isLoading}
            >
              Login with Google
            </TWButton>

            <Link
              href="/dashboard/register"
              className="text-center text-primary"
            >
              Register for an account
            </Link>
          </form>
        )}
      </Formik>
    </div>
  );
};

export default Login;
